"""Add token_blacklist table

Revision ID: c7fccc3cf6b1
Revises: 08bf1f3b114a
Create Date: 2025-01-20 08:17:52.769466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7fccc3cf6b1'
down_revision: Union[str, None] = '08bf1f3b114a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
